[tox]
minversion = 4.0.0
envlist =
       pylint,
       py{310,311,312,313,314,315},
       pyright,
       black,
       # docs,
       # coverage,
       build,
       install
skipsdist = True
skip_missing_interpreters = True

[gh-actions]
python =
    3.10: pylint, black, pyright, build, install, py310
    3.11: py311
    3.12: py312
    3.13: py313
    3.14: py314
    3.15: py315

[testenv]
module = mccli
deps = 
       -r requirements.txt
       pytest
       pytest-cov
       py310: coverage
       coverage: coverage-badge
       pyright: pyright
       pylint: pylint


[testenv:py310]
commands =
       pytest --cov={[testenv]module} --cov-report=term-missing:skip-covered
       coverage lcov

[testenv:py311]
commands =
       pytest --cov={[testenv]module} --cov-report=term-missing:skip-covered
       coverage lcov

[testenv:py312]
commands =
       pytest --cov={[testenv]module} --cov-report=term-missing:skip-covered
       coverage lcov

[testenv:py313]
commands =
       pytest --cov={[testenv]module} --cov-report=term-missing:skip-covered
       coverage lcov

[testenv:py314]
commands =
       pytest --cov={[testenv]module} --cov-report=term-missing:skip-covered
       coverage lcov

[testenv:py315]
commands =
       pytest --cov={[testenv]module} --cov-report=term-missing:skip-covered
       coverage lcov

[testenv:coverage]
commands =
       pytest --cov={[testenv]module} --cov-report=term-missing:skip-covered
       coverage-badge -f -o coverage.svg

[testenv:pylint]
commands = pylint --exit-zero {[testenv]module}

[testenv:black]
deps = black
commands = black --check --diff {[testenv]module}

[testenv:pyright]
commands = pyright {[testenv]module}

[testenv:docs]
deps =
       -r requirements.txt
       -r doc/source/requirements.txt
commands = sphinx-build doc/source doc/build


[testenv:build]
deps =
       build
       twine
allowlist_externals =
    bash
commands =
       bash -c 'rm -rf dist && python -m build --sdist .'
       twine check dist/*

[testenv:install]
deps =
       build
       twine
       pip
allowlist_externals =
    bash
commands =
       bash -c 'rm -rf dist && python -m build --sdist .'
       bash -c 'pip install dist/mccli-*.tar.gz'
       {[testenv]module} --version
